In [45]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

torch.manual_seed(1)

model 에서 여러개의 data 를 넣는 방법을 알아야겠네.

linear(n, m) 은 단일 데이터에 대한건데... 음

In [15]:
## linear regression

# hyper parameters
learning_rate = 0.01
n_epoch = 1000

# data
x_train = torch.rand(3).unsqueeze(1) # 만약 unsqueeze 를 뺀다면?
y_train = x_train + 0.1 * torch.rand(3).unsqueeze(1)

# model
model = nn.Linear(1, 1) # 1-dim vector -> 1-dim vector

# optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for _ in range(n_epoch):
    y_predict = model(x_train)
    loss = F.mse_loss(y_predict, y_train)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9855]], requires_grad=True), Parameter containing:
tensor([0.0732], requires_grad=True)]


In [56]:
## multivariate linear regression

# hyper parameters
learning_rate = 1e-9
n_epoch = 100000

# data
x_train = torch.rand(5, 3)
y_train = 0.7 * x_train[:, 0] + \
          0.8 * x_train[:, 1] + \
          0.3 * x_train[:, 2] + 0.01 * torch.rand(5)

y_train = y_train.unsqueeze(-1)

lm = nn.Linear(3, 1)

optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

for _ in range(n_epoch):
    optimizer.zero_grad()
    
    y_predict = lm(x_train)
    loss = F.mse_loss(y_predict, y_train)
    
    loss.backward()
    optimizer.step()
    
print(list(lm.parameters()))

[Parameter containing:
tensor([[-0.2988,  0.1252, -0.2102]], requires_grad=True), Parameter containing:
tensor([-0.1297], requires_grad=True)]


In [54]:
y_train, y_predict

(tensor([[1.1145],
         [1.2301],
         [1.1904],
         [1.0504],
         [1.3584]]),
 tensor([[-0.0439],
         [-0.0966],
         [ 0.0944],
         [-0.2528],
         [-0.1229]], grad_fn=<AddmmBackward>))